import LocalizedStrings from 'react-localization';

let info_strings = new LocalizedStrings({
  gr: {
    title: "Πληροφορίες",
    close: "Κλείσιμο",
    atm_analytics_short: "Πληροφορίες σχετικά με την ανάλυση επιπέδου πληρότητας ΑΤΜ.",
    atm_analytics_full: "Το παρόν διάγραμμα παρουσιάζει μία ανάλυση του επιπέδου πληρότητας για το επιλεγμένο ΑΤΜ σε βάθος χρόνου. Κάθε σημείο του διαγράμματος αποτελεί μία εγγραφή στην βάση δεδομένων και μας δείχνει το επίπεδο πληρότητας αποθέματος μετρητών με τιμές από 0 ( άδειο ) έως 1.0 ( 100% πληρότητα ). Αποτελεί μία ανάλυση της χρονοσειράς που χρησιμοποιείται για την εκπαίδευση των μοντέλων πρόβλεψης του επιλεγμένου ΑΤΜ.",
    supply_analytics_short: "Πληροφορίες σχετικά με την ανάλυση συμβάντων εφοδιασμού.",
    supply_analytics_full: "Το παρόν διάγραμμα παρουσιάζει μία ανάλυση του αριθμού συμβάντων εφοδιασμού ανά ΑΤΜ. Κάθε σημείο του διαγράμματος αποτελεί το πλήθος καταγεγραμμένων συμβάντων για ένα συγκεκριμένο ΑΤΜ, ο κωδικός του οποίο φαίνεται στον οριζόντιο άξονα του διαγράμματος. Το συγκεκριμένο διάγραμμα μας επιτρέπει να έχουμε μία οπτική αναπαράσταση του πλήθους συμβάντων και του πλήθους των ΑΤΜ που έχουν πιο συχνές ή πιο αραιές ενέργειες εφοδιασμού.",
    timeseries_analytics_short: "Πληροφορίες σχετικά με την ανάλυση δεδομένων χρονοσειρών.",
    timeseries_analytics_full: "Το παρόν διάγραμμα παρουσιάζει μία ανάλυση των δεδομένων χρονοσειρών που χρησιμοποιούνται για την εκπαίδευση των μοντέλων πρόβλεψης διαθέσημου αποθέματος των ΑΤΜ. Κάθε σημείο παρουσιάζει διάφορα στοιχεία για κάποιο συγκεκριμένο ΑΤΜ, ο κωδικός του οποίου παρουσιάζεται στον οριζόντιο άξονα του διαγράμματος. Συγκεκριμένα, οι γραμμές 'Μέση', 'Ελάχιστη', 'Μέγιστη' και 'Ενδιάμεση' παρουσιάζουν την μέση, ελάχιστη, μέγιστη και ενδιάμεση, αντίστοιχα, διαφορά σε αριθμό ημερών από δύο διαδοχικά συμβάντα εφοδιασμού για κάθε ΑΤΜ. Αυτές οι τιμές μας επιτρέπουν να εκτιμήσουμε την ποιότητα των χρονοσειρών που σχετίζονται με το συγκεκριμένο ΑΤΜ καθώς όσο μεγαλύτερη είναι η διαφορά ημερών τόσο πιο αραιά είναι τα δεδομένα μας και τόσο περισσότερη προ-επεξεργασία απαιτούν. Η γραμμή 'Εγγραφές' δείχνει τον συνολικό αριθμό συμβάντων εφοδιασμού για κάθε ΑΤΜ που αποτελεί και τον αριθμό εγγραφών στην βάση δεδομένων που αφορούν το ΑΤΜ. Τέλος, η γραμμή 'Κάλυψη' μας δείχνει το ποσοστό του συνολικού χρόνου για το οποίο το ΑΤΜ έχει δεδομένα. Κάθε σημείο του διαγράμματος κάλυψης έχει τιμή από 0 έως 1 που αντιστοιχεί σε 0% έως 100% και προκύπτει από τον λόγο της διαφοράς ημερών μεταξύ του πρώτου και του τελευταίο συμβάντως τροφοδοσίας προς τον συνολικό αριθμό ημερών του έτους που αναλύουμε.",
    prediction_csv_short: "Πληροφορίες σχετικά με την αναμενόμενη δομή του αρχείου CSV.",
    prediction_csv_full: "Το αναμενόμενο αρχείου CSV πρέπει να είναι χωρισμένο με τον χαρακτήρα ';' και ως δεκαδικό να έχει τον χαρακτήρα '.'. <br/>Πρέπει να περιλαμβάνει τρεις στήλες: 'ATM', 'date', 'value' όπου η πρώτη στήλη είναι ο κωδικός του ΑΤΜ, η δεύτερη η ημερομηνία μέτρησης σε μορφή 'dd/MM/YYYY' και η τρίτη το ποσοστό πληρότητας που μετρήθηκε ως δεκαδικός αριθμός από 0 έως 1.",
    optimization_csv_short: "Πληροφορίες σχετικά με την αναμενόμενη δομή του αρχείου CSV.",
    optimization_csv_full: "Το αναμενόμενο αρχείου CSV πρέπει να είναι χωρισμένο με τον χαρακτήρα ';' και ως δεκαδικό να έχει τον χαρακτήρα '.'. <br/>Πρέπει να περιλαμβάνει τρεις στήλες: 'ATM', 'date', 'value' όπου η πρώτη στήλη είναι ο κωδικός του ΑΤΜ, η δεύτερη η ημερομηνία μέτρησης σε μορφή 'dd/MM/YYYY' και η τρίτη το ποσοστό πληρότητας που μετρήθηκε ως δεκαδικός αριθμός από 0 έως 1.",
    dataset_zip_short: "Πληροφορίες σχετικά με την αναμενόμενη δομή του αρχείου ZIP.",
    dataset_zip_full: "Το αναμενόμενο αρχείο ZIP πρέπει να περιλαμβάνει: <ul><li>Ένα αρχείο τύπου xlsx (Excel) με όνομα 'ΕΦΟΔΙΑΣΜΟΙ.xlsx' με τα συμβάντα εφοδιασμών.</li><li>Ένα αρχείο τύπου xlsx (Excel) με όνομα 'ΕΦΟΔΙΑΣΜΟΙ_test.xlsx' με τα συμβάντα εφοδιασμών για δοκιμή και αξιολόγηση των μοντέλων.</li><li>Ένα φάκελο με όνομα 'outage' με στοιχεία σφαλμάτων ανά ημέρα. Ο φάκελος περιλαμβάνει ένα φάκελο ανά μήνα με όνομα 'MM-mmm_YYYY_off-site', για παράδειγμα για τον Ιανουάριο του 2023 θα ήταν '01-Jan_2023_off-site'. Κάθε τέτοιος φάκελος έχει ένα αρχείο Excel με την ημερήσια καταγραφή σφαλμάτων όλων των ΑΤΜ για κάθε ημέρα του μήνα.</li></ul>.",
  },
  en: {
    title: "Information",
    close: "Close",
    atm_analytics_short: "Information regarding the capacity level of ATMs.",
    atm_analytics_full: "The presented diagram visualizes a capacity level analysis of the selected ATM through the progress of time. Each point of the diagram is visualizing a record in the database and shows the percentage of available cash supply, having values ranginh from 0 ( empty ) to 1.0 ( 100% capacity ). It is an analysis of the timeseries used to train the prediction models regarding the specified ATM.",
    supply_analytics_short: "Information regarding the supply events analysis.",
    supply_analytics_full: "The present diagram is visualizing an analysis of the amount of supply events recorded per ATM. Each point in the diagram represents the total quantity of recorded supply event for a specific ATM. The code of each ATM is provided in the horizontal axis. This diagram allows us to have a first visual representation of the quanity of supply events in the database and the quantity of ATMs that are supplied more or less often.",
    timeseries_analytics_short: "Information regarding the timeseries analysis.",
    timeseries_analytics_full: "The present diagram is visualizing an analysis of the timeseries datasets used for the training of the available cash prediction models. Each point presents various information for a specific ATM, the ID code of which is presented in the horizontal axis of the diagram. In detail, the lines 'Average', 'Minimum', 'Maximum' and 'Median' visualize the average, minimum, maximum and median distance of days between two consecutive supply events for each specific ATM. These values allow us to estimate the quality of the timeseries that are connected to the specified ATM, since as the difference in days grows the dataset becomes more sparse, requiring more preprocessing. The line 'Records' shows the total number of supply events recorded for each ATM. The line 'Coverage' depicts the percentage of the total dataset duration covered by the data related to the specified ATM. Every point of the diagram shows a value ranging from 0 to 1, meaning 0% to 100%, which is the difference between the last and first supply event for the specified ATM divided by the total number of days in the monitored duration.",
    prediction_csv_short: "Information regarding the expected structure of the CSV file.",
    prediction_csv_full: "The expected CSV file must be separated by the ';' character and use the '.' character as the decimal divider. <br/>It must contain three columns: 'ATM', 'date', 'value' with the first column being the ATM code, the second being the date of the measurement in 'dd/MM/YYYY' format and the third being the measured available cash capacity of the ATM as a decimal number in the 0 to 1 range.",
    optimization_csv_short: "Information regarding the expected structure of the CSV file.",
    optimization_csv_full: "The expected CSV file must be separated by the ';' character and use the '.' character as the decimal divider. <br/>It must contain three columns: 'ATM', 'date', 'value' with the first column being the ATM code, the second being the date of the measurement in 'dd/MM/YYYY' format and the third being the measured available cash capacity of the ATM as a decimal number in the 0 to 1 range.",
    dataset_zip_short: "Information regarding the expected structure of the ZIP file.",
    dataset_zip_full: "The expected ZIP file must include: <ul><li>A file of type xlsx (Excel) named 'ΕΦΟΔΙΑΣΜΟΙ.xlsx' containing the supply events.</li><li>A file of type xlsx (Excel) named 'ΕΦΟΔΙΑΣΜΟΙ_test.xlsx' with the supply events that will be used for model evaluation and testing.</li><li>A folder named 'outage' with statistics about daily ATM faults. The folder contains a filder per month named using the 'MM-mmm_YYYY_off-site' format, for example the month January of 2023 woulf be named '01-Jan_2023_off-site'. Each of these folder contains an Excel file with the daily statistics of ATM faults for each day of the month.</li></ul>.",
  }
});

export default info_strings;